variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"

stages:
    - test
    - build
    
sonarcloud-check:
    image: maven:latest
    stage: test
    cache:
        key: "${CI_JOB_NAME}"
        paths:
            - .sonar/cache
    script:
        - mvn verify jacoco:report sonar:sonar
    only:
        - master

test:
    stage: test
    image: maven:latest
    script:
        - mvn clean test
    
build:
    stage: build
    image: openjdk:11.0.5-slim
    script:
        - mvn clean verify
    artifacts:
        paths:
            - target
       